import "@/styles/globals.css";

import type { Metadata } from "next";
import { Footer } from "@/components/footer";
import { Header } from "@/components/header";
import { TRPCReactProvider } from "@/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html className={`font-sans`} lang="en">
      <body>
        <TRPCReactProvider>
          <Header />

          {children}

          <Footer />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
